### ISSUE TITLE
file size limit

### ISSUE THREAD

**Issue by brooksomics** [claczny/busybee_web#3]
On the [FAQ](https://ccb-microbe.cs.uni-saarland.de/busybee/fqa/) you mention a command line version. How can I access this? Most of my assemblies are larger than the current 200 Mb limit.

**Comment by claczny** [comment]
Dear @brooksomics,

thank you very much for your interest in BusyBee Web.

Due to repeated requests, we have increased the upload filesize limit to 500 Mb.

Best,

Cedric
